[next] Port zos-logs SDK to vNext
zowe/zowe-cli pull request #1225
Opened 2021-12-01 21:28 UTC by t1m0thyj

Please review this PR, but don't merge it. Note that "next" is the head branch rather than the base branch, since I accidentally pushed changes directly to "next" branch 😢

2021-12-01 21:54 UTC, awharn approved these changes

2021-12-02 14:58 UTC, gejohnston requested changes
I think an item in the Readme doc needs to be changed.

2021-12-02 14:58 UTC, gejohnston commented on packages/zoslogs/README.md
> +  const session: Session = ZosmfSession.createBasicZosmfSession(defaultZosmfProfile);
In @next createBasicZosmfSession does not exist, so the example in the readme will not work for consumers.

2021-12-02 20:20 UTC, t1m0thyj commented
Closing this PR, will open a separate one to address the comments.

2021-12-02 20:20 UTC, closed without merging