Add stdin example
zowe/zowe-cli pull request #1331
Opened 2022-03-07 18:36 UTC by awharn

Fixes #1284
Also fixes a system test snapshot that is failing.

Signed-off-by: Andrew W. Harn <andrew.harn@broadcom.com>

2022-03-07 20:39 UTC, t1m0thyj approved these changes

2022-03-07 21:28 UTC, gejohnston requested changes
Minor wording suggestion.

2022-03-07 21:28 UTC, gejohnston commented on packages/cli/src/zosjobs/-strings-/en.ts
> +                        DESCRIPTION: "Submit the JCL in the file \"iefbr14.txt\" via standard in on Windows",
Both the redirect ( < ) and pipe ( | ) techniques work on both Windows and *nix. You may want to change the wording to reflect that they are two alternative techniques.

2022-03-08 19:19 UTC, gejohnston approved these changes
Thanks for changing the text. It was technically correct, but the rewording may avoid confusion.

2022-03-08 21:19 UTC, zFernand0 approved these changes

2022-03-09 16:50 UTC, merged