Update read me
zowe/zowe-cli pull request #1603
Opened 2023-01-17 18:23 UTC by ATorrise

Updating README to be more of a comprehensive one-stop-shop for zowe cli help. Including previously missing yet very impactful links to webhelp, zowe medium tutorials, sdk help. Adding the difference between V1 and V2 to our FAQ. Included some spacing differences to better legibility.

2023-01-18 17:38 UTC, KevinLoesch1 approved these changes

2023-01-18 17:59 UTC, anaxceron approved these changes
Good updates, thank you for doing this! Left a few comments about minor issues.

2023-01-18 18:38 UTC, gejohnston requested changes
I have one small suggested addition. Otherwise, everything looks fine to me.

2023-01-18 18:38 UTC, gejohnston commented on README.md
> +To view the Web Help for all Zowe CLI commands and contributed plug-ins, see the [Zowe CLI Web Help](https://docs.zowe.org/stable/web_help/index.html). To view all locally accessible commands, run `z
I suggest that we still point readers to the docs directory in addition to the other sources of documentation that you added.

Something like:

    Engineering design documentation is contained in the 'docs' directory in this repository.

2023-01-19 16:23 UTC, ATorrise commented on README.md
> +    Connection details can be managed efficiently within one file, promoting a global configuration that can be shared across teams and mainframe services. For more information on how to use profiles
Thank you for your comments, @anaxceron !

2023-01-19 20:32 UTC, gejohnston approved these changes

2023-01-19 20:52 UTC, merged