Update RUST dependencies and audit workflow
zowe/zowe-cli pull request #1655
Opened 2023-03-15 13:53 UTC by awharn

Updates the daemon dependencies and the RUST workflow to find additional issues, like yanked crates.

2023-03-15 14:19 UTC, zFernand0 approved these changes
Thanks for updating `bumpalo` 🥳 
And also for updating the workflow 😋 

LGTM! 😋

2023-03-15 14:25 UTC, t1m0thyj requested changes
Will approve once additional warnings that appear with `--deny warnings` flag have been addressed 🙂

2023-03-15 18:24 UTC, traeok approved these changes
LGTM, thanks @awharn !

2023-03-16 16:43 UTC, gejohnston approved these changes

2023-03-16 20:40 UTC, t1m0thyj approved these changes

2023-03-16 20:40 UTC, t1m0thyj commented on .github/workflows/rust-cli-publish.yml
> -        gtar -cvzf zowe.tgz zowe
Previously we had to use `gtar` to work around a bug where `tar` on MacOS included an extra file in the archive: https://github.com/zowe/zowe-cli/pull/1311

This seems to no longer be a problem, so I'm cool with using `tar` 🙂

2023-03-16 20:40 UTC, t1m0thyj commented on .github/workflows/rust-cli.yml
Noticed that we have duplicate runs of this workflow on `push` and `pull_request` events. Do we want to add the same condition we have in other workflows to skip duplicate runs?
`if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) && !contains(github.event.head_commit.message, '[ci skip]')`

2023-03-17 12:44 UTC, t1m0thyj approved these changes

2023-03-17 17:28 UTC, merged