Update pipelines
zowe/zowe-cli pull request #1712
Opened 2023-05-03 19:27 UTC by awharn

Update the pipelines to use newer workflows and the new alternative to set-output

2023-05-04 17:27 UTC, t1m0thyj commented on .github/workflows/zowe-cli.yml
Now that Octorelease v1 is released, should we update this workflow to use the new tags?

* `zowe-actions/octorelease@master` -> `zowe-actions/octorelease@v1`
* `zowe-actions/octorelease-script@master` -> `zowe-actions/octorelease/script@v1`
  ^ note the change from a hyphen to a slash

2023-05-05 12:00 UTC, zFernand0 reviewed
LGTM! 😋 
thanks for updating the stale and auto-comment versions too.
I'll wait until `octorelease@v1` is updated before approving! 😋

2023-05-08 14:18 UTC, zFernand0 requested changes
LGTM! 😋 
will approve once Timothy's comment is addressed 🥳 

---

Also, should we add the PR template?
https://github.com/zowe/imperative/blob/master/.github/PULL_REQUEST_TEMPLATE.md

2023-05-09 03:54 UTC, t1m0thyj approved these changes

2023-05-09 03:55 UTC, t1m0thyj approved these changes

2023-05-09 12:52 UTC, zFernand0 approved these changes

2023-05-10 14:22 UTC, merged