Update workflows v1
zowe/zowe-cli pull request #1714
Opened 2023-05-04 19:13 UTC by awharn

Updates zowe-v1-lts workflows to supported versions and remove Node 14 support

2023-05-08 14:14 UTC, zFernand0 requested changes
Changes LGTM!
Just left one small comment 😋

2023-05-08 14:14 UTC, zFernand0 commented on .github/workflows/audit.yml
|If it's ok, can we add the `zowe-v?-lts` branch to the following workflows:
- audit
- changelog
- linter (just needs to change the `v1` with `v?` 😋 

Here is an example
```yaml
on:
  pull_request:
    branches:
      - master
      - zowe-v?-lts
```

2023-05-09 03:55 UTC, t1m0thyj approved these changes

2023-05-09 13:00 UTC, zFernand0 requested changes

2023-05-09 13:00 UTC, zFernand0 commented on .github/workflows/audit.yml
> -        node-version: 14.x
should we use `lts/*`?

2023-05-09 13:00 UTC, zFernand0 commented on .github/workflows/audit.yml
this same comment may apply to the master workflows 😋

2023-05-10 14:26 UTC, zFernand0 requested changes
should we add the `zowe-v?-lts` to the `audit` and `changelog` workflows?

2023-05-10 15:04 UTC, awharn commented
> should we add the `zowe-v?-lts` to the `audit` and `changelog` workflows?

Wouldn't we want to make that change on the master branch instead of this one? That is the branch's workflows that would apply to zowe-v2-lts, zowe-v3-lts, etc.

2023-05-10 15:06 UTC, zFernand0 approved these changes

2023-05-10 15:06 UTC, merged