Fix abstract rest client (4 of 4) (CLI Migration V2)
zowe/zowe-cli pull request #1817
Opened 2023-10-04 14:05 UTC by awharn

**What It Does**
Fixes the abstract rest client's implementation of normalization

**How to Test**

**Review Checklist**
I certify that I have:
- [x] tested my changes
- [x] added/updated automated tests
- [x] updated the changelog
- [x] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

2023-10-04 19:12 UTC, traeok approved these changes

2023-10-05 12:06 UTC, t1m0thyj requested changes
Will approve once changelog update is added

2023-10-05 17:03 UTC, gejohnston approved these changes

2023-10-05 17:06 UTC, t1m0thyj approved these changes
LGTM, thanks @awharn!

2023-10-05 17:56 UTC, merged