standardizing error handling
zowe/zowe-cli pull request #2062
Opened 2024-02-22 21:42 UTC by ATorrise

**What It Does**
Bring standardization of error handling from zosjobs to zosfiles

**How to Test**

**Review Checklist**
I certify that I have:
- [ ] tested my changes
- [ ] added/updated automated tests
- [ ] updated the changelog
- [ ] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**
### Output for `zowe jobs submit lf noexist`
>#### Old Handling
>![image](https://github.com/zowe/zowe-cli/assets/112635587/982483cf-1b9a-47fa-aa6e-7996b89a8704)
>
>#### New Handling: 
>![image](https://github.com/zowe/zowe-cli/assets/112635587/94dd206a-76a4-441f-83a7-ba8b1a4accbe)

### Output for `zowe jobs submit lf noexist`
>![image](https://github.com/zowe/zowe-cli/assets/112635587/fcb3c279-4431-4de8-a02c-20c2620cac2c)

2024-02-27 21:40 UTC, gejohnston requested changes
I suggested a modification in the changelog.

2024-02-27 21:40 UTC, gejohnston commented on packages/cli/CHANGELOG.md
> -## `7.23.3`
I do not think that we will want recent V2 changelog entries to be deleted. They should remain.

2024-02-27 21:54 UTC, gejohnston commented
I am a little confused about the objective of the story itself.

A user specifies a non-existent file and the error message implies that the command has an internal logic failure. It blames the command handler for the error and displays a stack trace.

Should we instead capture the root error message 'no such file or directory' and display it in a format similar to the more user friendly format utilized for REST request errors that we used in a pull request several months ago?

2024-02-27 22:15 UTC, gejohnston commented
Note that the current full zos-files error message is:

```
zowe files upload ftds local remote
Unable to perform this operation due to the following problem.
Node.js File System API error

Response From Service
Error: ENOENT: no such file or directory, lstat 'C:\ourstuff\records\Broadcom\zowe\tech_info\config_files\local'

Diagnostic Information
Error: ENOENT: no such file or directory, lstat 'C:\ourstuff\records\Broadcom\zowe\tech_info\config_files\local'
```

The format above was created in response to another issue about unfriendly error messages.

Perhaps we should make the zos-jobs messages adhere to the format used by zos-files?

2024-02-28 14:10 UTC, adam-wolfe commented
After looking at this some more it seems like the best thing to do would be to not show a stack trace for the file not found error. Currently, in the latest versions of V2 and V3, the `jobs submit lf` command still displays a stack trace. I think we would want the jobs command failure to match the `zowe files upload` error message format.

2024-03-06 14:38 UTC, t1m0thyj commented
Closing in favor of #2078

2024-03-06 14:38 UTC, closed without merging