Dir to uss encoding flag
zowe/zowe-cli pull request #2350
Opened 2024-11-04 20:52 UTC by jace-roell

**What It Does**

**How to Test**

**Review Checklist**
I certify that I have:
- [ ] tested my changes
- [ ] added/updated automated tests
- [ ] updated the changelog
- [ ] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

2024-11-05 20:57 UTC, t1m0thyj approved these changes
LGTM, thanks @jace-roell for the quick fix and for adding a system test!

2024-11-05 21:44 UTC, traeok approved these changes
LGTM, thanks for adding the encoding flag! 😋

2024-11-05 21:44 UTC, traeok commented on packages/cli/CHANGELOG.md
> +- BugFix: Added support for `--encoding` flag to `zowe upload dir-to-uss` to allow for encoding uploaded directories for command group consitency [#2337](https://github.com/zowe/zowe-cli/issues/2337)
```suggestion
- BugFix: Added support for `--encoding` flag to `zowe upload dir-to-uss` to allow for encoding uploaded directories for command group consistency. [#2337](https://github.com/zowe/zowe-cli/issues/2337)
```

2024-11-05 21:44 UTC, traeok commented on packages/zosfiles/CHANGELOG.md
> +- BugFix: Added support for `--encoding` flag to `zowe upload dir-to-uss` to allow for encoding uploaded directories for command group consitency [#2337](https://github.com/zowe/zowe-cli/issues/2337)
```suggestion
- BugFix: Added support for `--encoding` flag to `zowe upload dir-to-uss` to allow for encoding uploaded directories for command group consistency. [#2337](https://github.com/zowe/zowe-cli/issues/2337)
```

2024-11-06 20:10 UTC, anaxceron reviewed
Requesting minor edits to the changelog entries

2024-11-06 20:10 UTC, anaxceron commented on packages/cli/CHANGELOG.md
> +- BugFix: Added support for `--encoding` flag to `zowe upload dir-to-uss` to allow for encoding uploaded directories for command group consistency. [#2337](https://github.com/zowe/zowe-cli/issues/233
Please add articles and add "command": "Added support for **the** `bbb` flag to **the** `zzz` **command** to allow ... "

2024-11-06 20:10 UTC, anaxceron commented on packages/zosfiles/CHANGELOG.md
> +- BugFix: Added support for `--encoding` flag to `zowe upload dir-to-uss` to allow for encoding uploaded directories for command group consistency. [#2337](https://github.com/zowe/zowe-cli/issues/233
same comment as above

2024-11-07 14:02 UTC, ATorrise requested changes

2024-11-07 14:02 UTC, ATorrise commented on packages/cli/src/zosfiles/upload/dtu/DirToUSSDir.definition.ts
>      ],
i like to include an example of using a new option that i added that way people know exactly how they can format their command when viewing the help. if others thumbs up would you mind adding an encoding example to the examples array?
```suggestion
          {
            description: strings.EXAMPLES.EX6, //youd have to edit this file too
            options: `"local_dir" "/a/ibmuser/my_dir" --encoding "IBM-1047"`
        }
```

2024-11-07 14:03 UTC, ATorrise commented on packages/cli/src/zosfiles/upload/dtu/DirToUSSDir.definition.ts
>      ],
the suggested change correlates to lines 78-79 not 57-60. it was hard to indicate this on the extension i was using to create this review

2024-11-07 17:47 UTC, gejohnston approved these changes

2024-11-07 19:22 UTC, ATorrise approved these changes

2024-11-07 20:42 UTC, awharn approved these changes

2024-11-08 15:48 UTC, zFernand0 approved these changes
LGTM as-is! 
but left a couple of comments with some minor changes 😋

2024-11-08 15:48 UTC, zFernand0 commented on packages/zosfiles/CHANGELOG.md
> +- BugFix: Added support for the `--encoding` flag to the `zowe upload dir-to-uss` to allow for encoding uploaded directories for command group consistency. [#2337](https://github.com/zowe/zowe-cli/is
Technically there is no need to have a changelog for the zosfiles sdk in this case.
It's fine to keep it, but if you plan to remove it, we may need to use the `no-changelog` label

2024-11-08 15:48 UTC, zFernand0 commented on packages/zosfiles/src/methods/upload/Upload.ts
> +
trailing spaces lint warnings

<img width="1028" alt="image" src="https://github.com/user-attachments/assets/90dcdc88-708f-4fa8-ba3e-61bac82a2187">

2024-11-08 18:01 UTC, anaxceron approved these changes

2024-11-08 19:07 UTC, merged