add tagging for bufferToUss
zowe/zowe-cli pull request #2378
Opened 2024-11-26 14:24 UTC by jace-roell

**What It Does**
Add file tagging to `Upload.bufferToUssFile`

**Review Checklist**
I certify that I have:
- [x] tested my changes
- [x] added/updated automated tests
- [x] updated the changelog
- [x] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

2024-11-26 16:09 UTC, ATorrise approved these changes

2024-12-04 19:17 UTC, anaxceron reviewed
Requesting an edit to the changelog : )

2024-12-06 15:33 UTC, zFernand0 requested changes
Took me a few minutes to figure out testing steps since `Upload.bufferToUssFile` is not exposed on any CLI command 😓 

Still testing since I ran into a small hiccup 😋 


<details><summary>Full testing script</summary>

```typescript
/* Save this file as `test.mjs` and run `node test.mjs` */

import { ProfileInfo } from "@zowe/imperative";
import { Upload } from "@zowe/zos-files-for-zowe-sdk";
import * as fs from "fs";
(async () => {
    // Load connection info from default z/OSMF profile
    const profInfo = new ProfileInfo("zowe");
    await profInfo.readProfilesFromDisk();
    const zosmfProfAttrs = profInfo.getDefaultProfile("zosmf");
    const zosmfMergedArgs = profInfo.mergeArgsForProfile(zosmfProfAttrs, { getSecureVals: true });
    const session = ProfileInfo.createSession(zosmfMergedArgs.knownArgs);

    const localFile = "package.json";
    const localFileContents = fs.readFileSync(localFile).toString();
    const remoteLocation = "/u/users/fernando/test-file1.txt";
    const options = { binary: true };
    // const response = await Upload.fileToUssFile(session, localFile, remoteLocation, options);
    const response = await Upload.bufferToUssFile(session, remoteLocation, Buffer.from(localFileContents), options);
    console.log(response);
})().catch((err) => {
    console.error(err);
    process.exit(1);
});
```
</details>

2024-12-06 15:33 UTC, zFernand0 commented on packages/zosfiles/__tests__/__unit__/methods/upload/Upload.unit.test.ts
> +            const chtagSpy = jest.spyOn(Utilities, "chtag");
should we `expect(thisSpy).toHaveBeenCalled()`?

2024-12-06 15:33 UTC, zFernand0 commented on packages/zosfiles/src/methods/upload/Upload.ts
> +            await Utilities.chtag(session, origUssname, Tag.TEXT, options.encoding);
it seems that this line is not covered?

Do we not have any tests that call the `bufferToUssFile` with no encoding? 🤯 
If not, maybe we should modify/add one 😋

2024-12-06 15:33 UTC, zFernand0 commented on packages/zosfiles/src/methods/upload/Upload.ts
>              commandResponse: ZosFilesMessages.dataSetUploadedSuccessfully.message,
also, not sure if we should make this change... but the apiResponse is empty 😋 
Should we at least specify which file the buffer was uploaded to? and maybe the contents of the buffer too? 😅 

<img width="491" alt="image" src="https://github.com/user-attachments/assets/f4c1883f-036e-421d-95e1-a2d37bdd3039">

2024-12-06 15:33 UTC, zFernand0 commented on packages/zosfiles/src/methods/upload/Upload.ts
> +            await Utilities.chtag(session, origUssname, Tag.BINARY);
I'm afraid that the file on the mainframe isn't tagged after testing.


```
- untagged    T=off -rw-r--r--    1 FERNANDO 0           4163 Dec  6 15:30 test-file1.txt
```
I could be doing something wrong though.

2024-12-06 16:55 UTC, awharn approved these changes

2024-12-06 18:55 UTC, zFernand0 approved these changes
LGTM! 😋 

When I tested it, I had a version of master cached in the build.
My mistake.
Files get tagged as expected 🙏

2024-12-06 18:56 UTC, zFernand0 commented
Besides the changelog updates requested by Ana, I think that my comments are mostly nice-to-have(s).
Don't feel obligated to implement them 😋 
Just figured I mention it to have other your thoughts on them 😋

2024-12-06 20:15 UTC, zFernand0 commented
The sonar cloud issues are related to very old commented out code.
Feel free to remove those commented out lines of code if you would like, but I don't believe that it should hold the PR from being merged 😋 
<img width="620" alt="image" src="https://github.com/user-attachments/assets/54f3e967-d311-4b3c-b67c-649d240d1f97">
<img width="871" alt="image" src="https://github.com/user-attachments/assets/7a5db386-ce30-4fab-851b-5cf81e6dc0bb">

2024-12-06 20:41 UTC, zFernand0 commented on packages/zosfiles/src/methods/upload/Upload.ts
>              commandResponse: ZosFilesMessages.dataSetUploadedSuccessfully.message,
Curious about your thoughts on this, @jace-roell?

2024-12-06 20:41 UTC, zFernand0 commented on packages/zosfiles/src/methods/upload/Upload.ts
> +            await Utilities.chtag(session, origUssname, Tag.TEXT, options.encoding);
Hey @jace-roell,
was this resolved in some un-pushed commit?

2024-12-09 17:16 UTC, anaxceron approved these changes
Requesting a minor edit to the changelog

2024-12-09 17:16 UTC, anaxceron commented on packages/zosfiles/CHANGELOG.md
> +- BugFix: Corrected `Upload.BufferToUssFile()` SDK function to properly tag uploaded files. [#2378](https://github.com/zowe/zowe-cli/pull/2378)
can we add "the" here?: "Corrected **the** `bbbb` SDK function to ... ."

2024-12-09 21:31 UTC, gejohnston approved these changes

2024-12-10 13:42 UTC, merged