Always treat encoding as a string for encoding.trim()
zowe/zowe-cli pull request #2392
Opened 2024-12-17 15:17 UTC by COBOL-Erik

encoding.trim() only works if encoding is interpreted as a string, but it might just be a number.

**What It Does**

**How to Test**

**Review Checklist**
I certify that I have:
- [X] tested my changes
- [x] added/updated automated tests
- [x] updated the changelog
- [X] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

2024-12-17 21:18 UTC, zFernand0 reviewed
Hey @COBOL-Erik,
The fix LGTM! 😋 

Curious if you could: 
- Add a Changelog entry to the `packages/zosjobs/src/CHANGELOG.md` file?
- (maybe) add a quick test for the encoding being a number? 🙏

2024-12-17 21:18 UTC, zFernand0 commented on packages/zosjobs/src/GetJobs.ts
> +            if(encoding.trim() != "") {parameters += "?fileEncoding=" + encoding;}
What do you think about combining the two if conditions? 😋 
```suggestion
        if (encoding != null && String(encoding).trim !== "") {
            parameters += "?fileEncoding=" + encoding;
        }
```

2024-12-17 22:02 UTC, COBOL-Erik commented
> Hey @COBOL-Erik, The fix LGTM! 😋
> 
> Curious if you could:
> 
> * Add a Changelog entry to the `packages/zosjobs/src/CHANGELOG.md` file?
> * (maybe) add a quick test for the encoding being a number? 🙏

Hi!
I added a change log entry. Not sure how I would add a test, though. Could you help me out?

2024-12-18 15:45 UTC, zFernand0 requested changes
Left a few comments to address.

Note: even though typescript should prevent people from calling the `getSpoolContentById` with a number e.g. `939` as the encoding value, nothing prevents people from bypassing it 😋 

And for the test, you could add a new one in:
- `packages/zosjobs/__tests__/__unit__/GetJobs.unit.test.ts`

And you could copy the following test to create a new one:
- `it("should return spool content from getSpoolContentById with encoding if z/OSMF response is mocked" ...`

And the resulting test might look something like this:
```typescript
        it("should return spool content from getSpoolContentById with encoding as a number if z/OSMF response is mocked", async () => {
            (ZosmfRestClient.getExpectString as any) = mockGetJobsStringData(GetJobsData.SAMPLE_JES_MSG_LG);
            const content = await GetJobs.getSpoolContentById(pretendSession, "MYJOB1", "JOB0123", 1, 939 as any);
            expect((ZosmfRestClient.getExpectString as any).mock.calls[0][1]).toContain("fileEncoding=939");
            expect(content).toEqual(GetJobsData.SAMPLE_JES_MSG_LG);
        });
```

2024-12-18 15:45 UTC, zFernand0 commented on packages/zosjobs/CHANGELOG.md
> +## `8.7.2`
```suggestion
## Recent Changes
```

2024-12-18 15:45 UTC, zFernand0 commented on packages/zosjobs/src/GetJobs.ts
> +        }
```suggestion
        if (encoding != null && String(encoding).trim() !== "") {
            parameters += "?fileEncoding=" + encoding;
        }
```

2024-12-20 15:53 UTC, COBOL-Erik commented
I have tried to do everything by the book now. I'm sure I have missed something... Where are we?

2024-12-23 20:49 UTC, t1m0thyj commented
> I have tried to do everything by the book now. I'm sure I have missed something... Where are we?

There were 2 commits that were not properly signed off:
> Commit sha: [2d7b68d](https://github.com/zowe/zowe-cli/pull/2392/commits/2d7b68db69fa392eb0a97eb00f20c8564e3d7067), Author: S38453, Committer: S38453; The sign-off is missing.
> Commit sha: [5ae8fbc](https://github.com/zowe/zowe-cli/pull/2392/commits/5ae8fbc8d72193bf2b46e386aebf660ea73acd7e), Author: S38453, Committer: S38453; Expected "S38453 [erik.weyler@seb.se](mailto:erik.weyler@seb.se)", but got "COBOL-Erik [32245335+COBOL-Erik@users.noreply.github.com](mailto:32245335+COBOL-Erik@users.noreply.github.com)".

I've rebased the PR to amend these commits so the DCO check should be passing now. As the Audit check is failing on master branch, you don't need to worry about it. 🙂 

In the future, please ensure when making Git commits that your Git author is set to `COBOL-Erik` (not S38453), and either pass the `--signoff` flag on the `git commit` command or include the "Signed-off-by" line in your commit message.

2024-12-24 14:29 UTC, t1m0thyj approved these changes
LGTM, thanks @COBOL-Erik!

2024-12-24 14:33 UTC, traeok approved these changes
Thanks for the fix @COBOL-Erik!

2024-12-24 14:37 UTC, merged