copy pds into new target data set functionality
zowe/zowe-cli pull request #2393
Opened 2024-12-20 17:15 UTC by pujal0909

**What It Does**

**How to Test**

**Review Checklist**
I certify that I have:
- [ ] tested my changes
- [ ] added/updated automated tests
- [ ] updated the changelog
- [ ] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

2025-01-06 18:47 UTC, t1m0thyj requested changes
Looks pretty good, thanks @pujal0909! Left a few comments

2025-01-06 18:47 UTC, t1m0thyj commented on packages/zosfiles/__tests__/__system__/methods/copy/Copy.system.test.ts
> +            });
Is this change necessary? This `afterEach` block seems redundant, since `before`/`after` blocks are inherited and there is already an `afterEach` block on line 55 that deletes these same data sets.

2025-01-06 18:47 UTC, t1m0thyj commented on packages/zosfiles/src/methods/copy/Copy.ts
> +            newDataSet = true;
When possible `const` is preferred over `let` 😋 This could be simplified to:
```suggestion
        const newDataSet = !targetDataSetExists;
        if (newDataSet) {
```

2025-01-06 18:47 UTC, t1m0thyj commented on packages/zosfiles/src/methods/copy/Copy.ts
> +        session: AbstractSession, fromPds: string, toPds: string, newDataSet: boolean): Promise<IZosFilesResponse> {
Since `copyPDS` is a public method we can't make breaking changes to the function signature. If we add a parameter like `newDataSet` it needs to be optional:
```suggestion
        session: AbstractSession, fromPds: string, toPds: string, newDataSet = false): Promise<IZosFilesResponse> {
```

2025-01-06 18:47 UTC, t1m0thyj commented on packages/zosfiles/src/methods/copy/Copy.ts
> +                    ? ZosFilesMessages.newDataSetCreated.message + ` - "${toPds}"`
We use the `ZosFilesMessages` class to define message strings in a common place so that they can be easily translated (in the future because we don't support i18n yet).

Please define the message with a `%s` placeholder so that the entire message is translatable. Then you can use the `util.format` function to replace the placeholder with a real value.
```typescript
    newDataSetCreated: {
        message: `New data set created - "%s"`
    },
```
```suggestion
                    ? util.format(ZosFilesMessages.newDataSetCreated.message, toPds)
```

2025-01-06 19:04 UTC, pujal0909 commented on packages/zosfiles/__tests__/__system__/methods/copy/Copy.system.test.ts
> +            });
Somehow that was added there by mistake. Thanks for catching that!

2025-01-06 20:50 UTC, t1m0thyj reviewed
Tested the functionality and it LGTM 🙂

@pujal0909 Please add a system test for the case where target data set does not exist.

Question for @adam-wolfe and @anaxceron - should we update the help text for the `zowe copy ds` command to explain that if the target data set does not exist, it will be created?

2025-01-06 20:50 UTC, t1m0thyj commented on packages/zosfiles/src/methods/copy/Copy.ts
> +    public static async dataSetExists(
If this method isn't used outside of this file, we may want to make it private for now.

2025-01-06 20:50 UTC, t1m0thyj commented on packages/zosfiles/src/methods/copy/Copy.ts
> +        const dataSetList = await List.dataSet(session, dataSetName, {attributes: true, start: dataSetName});
Are attributes needed or if we just need names can we list without them?

2025-01-06 21:02 UTC, adam-wolfe commented
> Tested the functionality and it LGTM 🙂
> 
> @pujal0909 Please add a system test for the case where target data set does not exist.
> 
> Question for @adam-wolfe and @anaxceron - should we update the help text for the `zowe copy ds` command to explain that if the target data set does not exist, it will be created?

I think so. I would change change this line: 
![image](https://github.com/user-attachments/assets/1641a66c-c0b0-4cd2-aa5f-2dfe2124cd79)

2025-01-07 20:23 UTC, anaxceron reviewed
Left a minor comment re: a changelog.

2025-01-07 20:23 UTC, anaxceron commented on packages/zosfiles/CHANGELOG.md
> +- Enhancement: The `Copy.dataset` function now creates a new data set if the inputted target data set does not exist. [#2349](https://github.com/zowe/zowe-cli/issues/2349)
Can we use another word besides "inputted"? Like "entered" or "selected" or "included"?

2025-01-07 20:44 UTC, traeok reviewed
Functionality LGTM, thanks Pujal! I had couple small requests for changes and a follow-up question...

---

In the event where a user tries to copy to the same data set, can we return early from the command? Currently, if I try copying a PDS from source `A.B.C` to the same destination (`A.B.C`), the command copies each member, even though the source and destination are identical:

![image](https://github.com/user-attachments/assets/b51dfba7-f7b6-4287-8535-9b35624dc75a)

2025-01-07 20:59 UTC, traeok commented on packages/zosfiles/CHANGELOG.md
> +- Enhancement: The `Copy.dataset` method now creates a new data set if the inputted target data set does not exist. [#2386](https://github.com/zowe/zowe-cli/pull/2386)
Please disregard, this comment was from earlier this morning and I see that this is now resolved 😅

2025-01-08 21:04 UTC, awharn commented on packages/zosfiles/src/methods/copy/Copy.ts
> +                    ? util.format(ZosFilesMessages.newDataSetCreated.message, toPds)
Would it make sense to instead have the calling function change the command response message if it created a new data set? I just ask because this function isn't creating the new data set itself.

2025-01-11 11:22 UTC, t1m0thyj approved these changes
LGTM, thanks @pujal0909!

2025-01-13 14:49 UTC, anaxceron approved these changes

2025-01-13 20:18 UTC, traeok approved these changes

2025-01-15 17:21 UTC, merged