fix(secrets): Reduce keychain unlock prompts on MacOS
zowe/zowe-cli pull request #2394
Opened 2024-12-21 01:40 UTC by t1m0thyj

**What It Does**

**How to Test**

**Review Checklist**
I certify that I have:
- [ ] tested my changes
- [ ] added/updated automated tests
- [ ] updated the changelog
- [ ] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

2024-12-23 15:30 UTC, traeok approved these changes
Changes make sense to me, thanks for the fix @t1m0thyj - pretty cool that `fmutex` leverages the scope of the guard to auto-release the lock 😋 

As discussed offline, failing tests are related to `glibc` segfault with `ava` - once `workerThreads: false` is added, the stages will pass. Thanks for looking into this as well!

2025-01-06 18:33 UTC, gejohnston requested changes
A small suggestion about the changelog. Otherwise ready to approve.

2025-01-06 18:33 UTC, gejohnston commented on packages/secrets/CHANGELOG.md
> +- BugFix: Reduced number of keychain unlock prompts on MacOS for simultaneous access to secrets by the same process.
The fix really addresses more than one process. I suggest the following wording:
... by multiple instances of the same application.

2025-01-06 21:52 UTC, gejohnston approved these changes

2025-01-07 14:10 UTC, jace-roell approved these changes

2025-01-07 18:48 UTC, t1m0thyj commented on packages/secrets/core/src/os/mac/mod.rs
> +        .join(format!("keyring_{}.lock", exe_path));
Resolved in https://github.com/zowe/zowe-cli/pull/2394/commits/265f087632d093ad42db0ff2608baf55f1f25d71

2025-01-07 20:26 UTC, anaxceron reviewed
We should add an issue or PR link to the changelog entry

2025-01-07 20:26 UTC, anaxceron commented on packages/secrets/CHANGELOG.md
> +- BugFix: Reduced number of keychain unlock prompts on MacOS for simultaneous access to secrets by multiple instances of the same application.
Please add an issue or PR link

2025-01-07 22:09 UTC, merged