Enhancement: Add progress tracking to DirToUSSDirHandler for file upl…
zowe/zowe-cli pull request #2399
Opened 2024-12-27 11:15 UTC by MAVRICK-1

**What It Does**  
This update enhances the `DirToUSSDirHandler` functionality:  
- Introduced progress tracking using `commandParameters.response.progress` to provide feedback during file uploads.  
- Reintroduced the `encoding` parameter in the upload options to ensure compatibility with various encoding configurations.  

fixed #2344 

**How to Test**  
1. Configure the handler with a valid session and set `encoding` in the upload options.  
2. Run the upload command with both `recursive` and non-recursive options.  
3. Verify that a progress bar is displayed during the upload process.  
4. Check the console log for properly formatted responses.  

**Review Checklist**  
I certify that I have:  
- [x] tested my changes  
- [ ] added/updated automated tests  
- [x] updated the changelog  
- [x] followed the [[contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)  

**Additional Comments**  
This update ensures better user feedback through progress tracking and retains support for encoding, making the handler more robust.

2024-12-27 11:16 UTC, MAVRICK-1 commented
@zFernand0 can you review my PR

2025-01-03 17:10 UTC, t1m0thyj requested changes
@MAVRICK-1 Thanks for your contribution! Please make the requested change so the project builds successfully

2025-01-03 17:10 UTC, t1m0thyj commented on packages/cli/src/zosfiles/upload/dtu/DirToUSSDir.handler.ts
> +        commandParameters.response.progress.startBar("Uploading files...");
The `startBar` method expects an `ITaskWithStatus` object rather than a string. Please update this to pass in the task object already defined in this handler:
```suggestion
        commandParameters.response.progress.startBar({ task: status });
```

2025-01-03 17:52 UTC, MAVRICK-1 commented
@t1m0thyj done

2025-01-03 20:15 UTC, t1m0thyj approved these changes
LGTM, thanks @MAVRICK-1!

2025-01-03 21:07 UTC, MAVRICK-1 commented
@t1m0thyj, I want to contribute more. Where can I learn more about  developing Zowe?

2025-01-06 15:36 UTC, t1m0thyj commented
> @t1m0thyj, I want to contribute more. Where can I learn more about developing Zowe?

@MAVRICK-1 Zowe has several components which all welcome new contributors 🙂 You can find a summary of each one here: https://docs.zowe.org/stable/getting-started/overview

Based on your interests and programming experience, you may find some components to be more appealing than others 😋  The Zowe server components are mostly written in Java and C, and the client components are written in a variety of languages: TypeScript, Python, Kotlin, etc.

I'd also recommend joining the [Open Mainframe Project Slack](https://slack.openmainframeproject.org/) if you want to get more involved with the Zowe community.

2025-01-06 16:37 UTC, zFernand0 approved these changes
Working as expected!
LGTM! 😋 

Thanks for the quick enhancement

2025-01-06 16:43 UTC, anaxceron reviewed
Left a comment re: changelog

2025-01-06 16:43 UTC, anaxceron commented on packages/imperative/CHANGELOG.md
> +- Enhancement: Added progress tracking to the `DirToUSSDirHandler` by using `commandParameters.response.progress` to show progress bars during file uploads. [#2334](https://github.com/zowe/zowe-cli/i
we should explain what `DirToUSSDirHandler` and `commandParameters.blah.blah` are: "... to the class/profile/cat/whatever `DirToBlahBlah` by using the `commandBlahBlah` function/class/cat/whatever to ..."

2025-01-06 18:02 UTC, gejohnston approved these changes

2025-01-06 20:52 UTC, traeok approved these changes

2025-01-07 19:43 UTC, merged