Moved the job card changes to the `next`
zowe/zowe-cli pull request #931
Opened 2021-01-29 17:07 UTC by abastyr

Job statement related changes from the `master` branch

2021-02-01 09:32 UTC, abastyr commented
@zFernand0 Hey, could you please check that error? The `checkTestsCompile` works on my machine, and it seems this error wasn't caused by my changes.

2021-02-02 13:36 UTC, zFernand0 commented
@abastyr, seems like `checkTestsCompile` worked on permutations of the (OS, Node_version) matrix. 😋 
However, Jenkins seems to be complaining about the conflicts.

To avoid having to deal with all of these, I'll recommend waiting for #902 to be merged into `main` and then we can update next with the newest features (including the `jobStatement`)

How does that sound? 😄

2021-02-03 09:06 UTC, abastyr commented
> @abastyr, seems like `checkTestsCompile` worked on permutations of the (OS, Node_version) matrix. 😋
> However, Jenkins seems to be complaining about the conflicts.
> 
> To avoid having to deal with all of these, I'll recommend waiting for #902 to be merged into `main` and then we can update next with the newest features (including the `jobStatement`)
> 
> How does that sound? 😄

OK, sounds good to me :)

2021-03-26 17:33 UTC, awharn requested changes

2021-03-26 17:33 UTC, awharn commented on packages/workflows/src/api/doc/IParamsCreateWorkflow.ts
> +    WorkflowName: string;
I noticed that some of these parameters on the interface are in UpperCamelCase, and some are in lowerCamelCase. I think we would want to be consistent in which one we are using, and most other interfaces seem to use lowerCamelCase.

2021-03-26 17:33 UTC, awharn commented on packages/workflows/src/api/doc/IParamsCreateWorkflowLocal.ts
> +    WorkflowName: string;
Same comment as IParamsCreateWorkflow

2021-03-31 15:07 UTC, zFernand0 commented
This PR is waiting for #902

2023-02-17 16:56 UTC, zFernand0 commented
Reasons for closing this PR:
- As it stands, there are 2 years worth of changes that need to be integrated with this enhancement. 
  - Not impossible but tedious.
- With the maturity of the `zowe.config.json` files, it's likely for this feature to have more adoption by storing the Job Statement as an object as a profile property.
  - [Dan's blog](https://medium.com/zowe/tip-how-to-store-zowe-cli-arguments-in-team-config-b96c7d366edc) may help when/if we decide to support these complex structures.
  - Example: 
    ```jsonc
      //...
      "jobStatement": [
          "//USERIDx JOB (ACCT#),",
          "//    CLASS=A,MSGCLASS=A,REGION=0M,NOTIFY=USERID"
      ],
    ```
- There was a possible breaking change in the initial implementation of #902 and worked around in this one.
  - We can discuss if it still makes sense to introduce this enhancement alongside the desired changes to the `createWorkflow` APIs for Zowe V3.

2023-02-17 16:56 UTC, closed without merging